
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `ShippingMethod` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ShippingMethod
 * 
 */
export type ShippingMethodModel = runtime.Types.Result.DefaultSelection<Prisma.$ShippingMethodPayload>

export type AggregateShippingMethod = {
  _count: ShippingMethodCountAggregateOutputType | null
  _min: ShippingMethodMinAggregateOutputType | null
  _max: ShippingMethodMaxAggregateOutputType | null
}

export type ShippingMethodMinAggregateOutputType = {
  id: string | null
  title: string | null
  providerName: string | null
  providerLogoId: string | null
  requireDateOfDelivery: boolean | null
  organizationId: string | null
  archivedAt: Date | null
  archivedBy: string | null
  publishedAt: Date | null
  publishedBy: string | null
  createdAt: Date | null
  createdBy: string | null
  updatedAt: Date | null
  updatedBy: string | null
}

export type ShippingMethodMaxAggregateOutputType = {
  id: string | null
  title: string | null
  providerName: string | null
  providerLogoId: string | null
  requireDateOfDelivery: boolean | null
  organizationId: string | null
  archivedAt: Date | null
  archivedBy: string | null
  publishedAt: Date | null
  publishedBy: string | null
  createdAt: Date | null
  createdBy: string | null
  updatedAt: Date | null
  updatedBy: string | null
}

export type ShippingMethodCountAggregateOutputType = {
  id: number
  title: number
  providerName: number
  providerLogoId: number
  requireDateOfDelivery: number
  organizationId: number
  archivedAt: number
  archivedBy: number
  publishedAt: number
  publishedBy: number
  createdAt: number
  createdBy: number
  updatedAt: number
  updatedBy: number
  _all: number
}


export type ShippingMethodMinAggregateInputType = {
  id?: true
  title?: true
  providerName?: true
  providerLogoId?: true
  requireDateOfDelivery?: true
  organizationId?: true
  archivedAt?: true
  archivedBy?: true
  publishedAt?: true
  publishedBy?: true
  createdAt?: true
  createdBy?: true
  updatedAt?: true
  updatedBy?: true
}

export type ShippingMethodMaxAggregateInputType = {
  id?: true
  title?: true
  providerName?: true
  providerLogoId?: true
  requireDateOfDelivery?: true
  organizationId?: true
  archivedAt?: true
  archivedBy?: true
  publishedAt?: true
  publishedBy?: true
  createdAt?: true
  createdBy?: true
  updatedAt?: true
  updatedBy?: true
}

export type ShippingMethodCountAggregateInputType = {
  id?: true
  title?: true
  providerName?: true
  providerLogoId?: true
  requireDateOfDelivery?: true
  organizationId?: true
  archivedAt?: true
  archivedBy?: true
  publishedAt?: true
  publishedBy?: true
  createdAt?: true
  createdBy?: true
  updatedAt?: true
  updatedBy?: true
  _all?: true
}

export type ShippingMethodAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ShippingMethod to aggregate.
   */
  where?: Prisma.ShippingMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShippingMethods to fetch.
   */
  orderBy?: Prisma.ShippingMethodOrderByWithRelationInput | Prisma.ShippingMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ShippingMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShippingMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShippingMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ShippingMethods
  **/
  _count?: true | ShippingMethodCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ShippingMethodMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ShippingMethodMaxAggregateInputType
}

export type GetShippingMethodAggregateType<T extends ShippingMethodAggregateArgs> = {
      [P in keyof T & keyof AggregateShippingMethod]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateShippingMethod[P]>
    : Prisma.GetScalarType<T[P], AggregateShippingMethod[P]>
}




export type ShippingMethodGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ShippingMethodWhereInput
  orderBy?: Prisma.ShippingMethodOrderByWithAggregationInput | Prisma.ShippingMethodOrderByWithAggregationInput[]
  by: Prisma.ShippingMethodScalarFieldEnum[] | Prisma.ShippingMethodScalarFieldEnum
  having?: Prisma.ShippingMethodScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ShippingMethodCountAggregateInputType | true
  _min?: ShippingMethodMinAggregateInputType
  _max?: ShippingMethodMaxAggregateInputType
}

export type ShippingMethodGroupByOutputType = {
  id: string
  title: string
  providerName: string
  providerLogoId: string | null
  requireDateOfDelivery: boolean | null
  organizationId: string
  archivedAt: Date | null
  archivedBy: string | null
  publishedAt: Date | null
  publishedBy: string | null
  createdAt: Date
  createdBy: string | null
  updatedAt: Date
  updatedBy: string | null
  _count: ShippingMethodCountAggregateOutputType | null
  _min: ShippingMethodMinAggregateOutputType | null
  _max: ShippingMethodMaxAggregateOutputType | null
}

type GetShippingMethodGroupByPayload<T extends ShippingMethodGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ShippingMethodGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ShippingMethodGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ShippingMethodGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ShippingMethodGroupByOutputType[P]>
      }
    >
  > 



export type ShippingMethodWhereInput = {
  AND?: Prisma.ShippingMethodWhereInput | Prisma.ShippingMethodWhereInput[]
  OR?: Prisma.ShippingMethodWhereInput[]
  NOT?: Prisma.ShippingMethodWhereInput | Prisma.ShippingMethodWhereInput[]
  id?: Prisma.StringFilter<"ShippingMethod"> | string
  title?: Prisma.StringFilter<"ShippingMethod"> | string
  providerName?: Prisma.StringFilter<"ShippingMethod"> | string
  providerLogoId?: Prisma.StringNullableFilter<"ShippingMethod"> | string | null
  requireDateOfDelivery?: Prisma.BoolNullableFilter<"ShippingMethod"> | boolean | null
  organizationId?: Prisma.StringFilter<"ShippingMethod"> | string
  archivedAt?: Prisma.DateTimeNullableFilter<"ShippingMethod"> | Date | string | null
  archivedBy?: Prisma.StringNullableFilter<"ShippingMethod"> | string | null
  publishedAt?: Prisma.DateTimeNullableFilter<"ShippingMethod"> | Date | string | null
  publishedBy?: Prisma.StringNullableFilter<"ShippingMethod"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ShippingMethod"> | Date | string
  createdBy?: Prisma.StringNullableFilter<"ShippingMethod"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"ShippingMethod"> | Date | string
  updatedBy?: Prisma.StringNullableFilter<"ShippingMethod"> | string | null
  providerLogo?: Prisma.XOR<Prisma.FileNullableScalarRelationFilter, Prisma.FileWhereInput> | null
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  shippingZones?: Prisma.ShippingZoneListRelationFilter
  orders?: Prisma.OrderListRelationFilter
}

export type ShippingMethodOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  providerName?: Prisma.SortOrder
  providerLogoId?: Prisma.SortOrderInput | Prisma.SortOrder
  requireDateOfDelivery?: Prisma.SortOrderInput | Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  archivedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  archivedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  publishedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  publishedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdBy?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  providerLogo?: Prisma.FileOrderByWithRelationInput
  organization?: Prisma.OrganizationOrderByWithRelationInput
  shippingZones?: Prisma.ShippingZoneOrderByRelationAggregateInput
  orders?: Prisma.OrderOrderByRelationAggregateInput
}

export type ShippingMethodWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  providerLogoId?: string
  AND?: Prisma.ShippingMethodWhereInput | Prisma.ShippingMethodWhereInput[]
  OR?: Prisma.ShippingMethodWhereInput[]
  NOT?: Prisma.ShippingMethodWhereInput | Prisma.ShippingMethodWhereInput[]
  title?: Prisma.StringFilter<"ShippingMethod"> | string
  providerName?: Prisma.StringFilter<"ShippingMethod"> | string
  requireDateOfDelivery?: Prisma.BoolNullableFilter<"ShippingMethod"> | boolean | null
  organizationId?: Prisma.StringFilter<"ShippingMethod"> | string
  archivedAt?: Prisma.DateTimeNullableFilter<"ShippingMethod"> | Date | string | null
  archivedBy?: Prisma.StringNullableFilter<"ShippingMethod"> | string | null
  publishedAt?: Prisma.DateTimeNullableFilter<"ShippingMethod"> | Date | string | null
  publishedBy?: Prisma.StringNullableFilter<"ShippingMethod"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ShippingMethod"> | Date | string
  createdBy?: Prisma.StringNullableFilter<"ShippingMethod"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"ShippingMethod"> | Date | string
  updatedBy?: Prisma.StringNullableFilter<"ShippingMethod"> | string | null
  providerLogo?: Prisma.XOR<Prisma.FileNullableScalarRelationFilter, Prisma.FileWhereInput> | null
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  shippingZones?: Prisma.ShippingZoneListRelationFilter
  orders?: Prisma.OrderListRelationFilter
}, "id" | "providerLogoId">

export type ShippingMethodOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  providerName?: Prisma.SortOrder
  providerLogoId?: Prisma.SortOrderInput | Prisma.SortOrder
  requireDateOfDelivery?: Prisma.SortOrderInput | Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  archivedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  archivedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  publishedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  publishedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdBy?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ShippingMethodCountOrderByAggregateInput
  _max?: Prisma.ShippingMethodMaxOrderByAggregateInput
  _min?: Prisma.ShippingMethodMinOrderByAggregateInput
}

export type ShippingMethodScalarWhereWithAggregatesInput = {
  AND?: Prisma.ShippingMethodScalarWhereWithAggregatesInput | Prisma.ShippingMethodScalarWhereWithAggregatesInput[]
  OR?: Prisma.ShippingMethodScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ShippingMethodScalarWhereWithAggregatesInput | Prisma.ShippingMethodScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ShippingMethod"> | string
  title?: Prisma.StringWithAggregatesFilter<"ShippingMethod"> | string
  providerName?: Prisma.StringWithAggregatesFilter<"ShippingMethod"> | string
  providerLogoId?: Prisma.StringNullableWithAggregatesFilter<"ShippingMethod"> | string | null
  requireDateOfDelivery?: Prisma.BoolNullableWithAggregatesFilter<"ShippingMethod"> | boolean | null
  organizationId?: Prisma.StringWithAggregatesFilter<"ShippingMethod"> | string
  archivedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ShippingMethod"> | Date | string | null
  archivedBy?: Prisma.StringNullableWithAggregatesFilter<"ShippingMethod"> | string | null
  publishedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ShippingMethod"> | Date | string | null
  publishedBy?: Prisma.StringNullableWithAggregatesFilter<"ShippingMethod"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ShippingMethod"> | Date | string
  createdBy?: Prisma.StringNullableWithAggregatesFilter<"ShippingMethod"> | string | null
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ShippingMethod"> | Date | string
  updatedBy?: Prisma.StringNullableWithAggregatesFilter<"ShippingMethod"> | string | null
}

export type ShippingMethodCreateInput = {
  id?: string
  title: string
  providerName: string
  requireDateOfDelivery?: boolean | null
  archivedAt?: Date | string | null
  archivedBy?: string | null
  publishedAt?: Date | string | null
  publishedBy?: string | null
  createdAt?: Date | string
  createdBy?: string | null
  updatedAt?: Date | string
  updatedBy?: string | null
  providerLogo?: Prisma.FileCreateNestedOneWithoutShippingMethodLogoForInput
  organization: Prisma.OrganizationCreateNestedOneWithoutShippingMethodsInput
  shippingZones?: Prisma.ShippingZoneCreateNestedManyWithoutShippingMethodInput
  orders?: Prisma.OrderCreateNestedManyWithoutShippingMethodInput
}

export type ShippingMethodUncheckedCreateInput = {
  id?: string
  title: string
  providerName: string
  providerLogoId?: string | null
  requireDateOfDelivery?: boolean | null
  organizationId: string
  archivedAt?: Date | string | null
  archivedBy?: string | null
  publishedAt?: Date | string | null
  publishedBy?: string | null
  createdAt?: Date | string
  createdBy?: string | null
  updatedAt?: Date | string
  updatedBy?: string | null
  shippingZones?: Prisma.ShippingZoneUncheckedCreateNestedManyWithoutShippingMethodInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutShippingMethodInput
}

export type ShippingMethodUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  providerName?: Prisma.StringFieldUpdateOperationsInput | string
  requireDateOfDelivery?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archivedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  archivedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  providerLogo?: Prisma.FileUpdateOneWithoutShippingMethodLogoForNestedInput
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutShippingMethodsNestedInput
  shippingZones?: Prisma.ShippingZoneUpdateManyWithoutShippingMethodNestedInput
  orders?: Prisma.OrderUpdateManyWithoutShippingMethodNestedInput
}

export type ShippingMethodUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  providerName?: Prisma.StringFieldUpdateOperationsInput | string
  providerLogoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requireDateOfDelivery?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  archivedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  archivedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingZones?: Prisma.ShippingZoneUncheckedUpdateManyWithoutShippingMethodNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutShippingMethodNestedInput
}

export type ShippingMethodCreateManyInput = {
  id?: string
  title: string
  providerName: string
  providerLogoId?: string | null
  requireDateOfDelivery?: boolean | null
  organizationId: string
  archivedAt?: Date | string | null
  archivedBy?: string | null
  publishedAt?: Date | string | null
  publishedBy?: string | null
  createdAt?: Date | string
  createdBy?: string | null
  updatedAt?: Date | string
  updatedBy?: string | null
}

export type ShippingMethodUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  providerName?: Prisma.StringFieldUpdateOperationsInput | string
  requireDateOfDelivery?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archivedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  archivedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ShippingMethodUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  providerName?: Prisma.StringFieldUpdateOperationsInput | string
  providerLogoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requireDateOfDelivery?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  archivedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  archivedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ShippingMethodListRelationFilter = {
  every?: Prisma.ShippingMethodWhereInput
  some?: Prisma.ShippingMethodWhereInput
  none?: Prisma.ShippingMethodWhereInput
}

export type ShippingMethodOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ShippingMethodNullableScalarRelationFilter = {
  is?: Prisma.ShippingMethodWhereInput | null
  isNot?: Prisma.ShippingMethodWhereInput | null
}

export type ShippingMethodCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  providerName?: Prisma.SortOrder
  providerLogoId?: Prisma.SortOrder
  requireDateOfDelivery?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  archivedAt?: Prisma.SortOrder
  archivedBy?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  publishedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
}

export type ShippingMethodMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  providerName?: Prisma.SortOrder
  providerLogoId?: Prisma.SortOrder
  requireDateOfDelivery?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  archivedAt?: Prisma.SortOrder
  archivedBy?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  publishedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
}

export type ShippingMethodMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  providerName?: Prisma.SortOrder
  providerLogoId?: Prisma.SortOrder
  requireDateOfDelivery?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  archivedAt?: Prisma.SortOrder
  archivedBy?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  publishedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
}

export type ShippingMethodScalarRelationFilter = {
  is?: Prisma.ShippingMethodWhereInput
  isNot?: Prisma.ShippingMethodWhereInput
}

export type ShippingMethodCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.ShippingMethodCreateWithoutOrganizationInput, Prisma.ShippingMethodUncheckedCreateWithoutOrganizationInput> | Prisma.ShippingMethodCreateWithoutOrganizationInput[] | Prisma.ShippingMethodUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.ShippingMethodCreateOrConnectWithoutOrganizationInput | Prisma.ShippingMethodCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.ShippingMethodCreateManyOrganizationInputEnvelope
  connect?: Prisma.ShippingMethodWhereUniqueInput | Prisma.ShippingMethodWhereUniqueInput[]
}

export type ShippingMethodUncheckedCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.ShippingMethodCreateWithoutOrganizationInput, Prisma.ShippingMethodUncheckedCreateWithoutOrganizationInput> | Prisma.ShippingMethodCreateWithoutOrganizationInput[] | Prisma.ShippingMethodUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.ShippingMethodCreateOrConnectWithoutOrganizationInput | Prisma.ShippingMethodCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.ShippingMethodCreateManyOrganizationInputEnvelope
  connect?: Prisma.ShippingMethodWhereUniqueInput | Prisma.ShippingMethodWhereUniqueInput[]
}

export type ShippingMethodUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.ShippingMethodCreateWithoutOrganizationInput, Prisma.ShippingMethodUncheckedCreateWithoutOrganizationInput> | Prisma.ShippingMethodCreateWithoutOrganizationInput[] | Prisma.ShippingMethodUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.ShippingMethodCreateOrConnectWithoutOrganizationInput | Prisma.ShippingMethodCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.ShippingMethodUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.ShippingMethodUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.ShippingMethodCreateManyOrganizationInputEnvelope
  set?: Prisma.ShippingMethodWhereUniqueInput | Prisma.ShippingMethodWhereUniqueInput[]
  disconnect?: Prisma.ShippingMethodWhereUniqueInput | Prisma.ShippingMethodWhereUniqueInput[]
  delete?: Prisma.ShippingMethodWhereUniqueInput | Prisma.ShippingMethodWhereUniqueInput[]
  connect?: Prisma.ShippingMethodWhereUniqueInput | Prisma.ShippingMethodWhereUniqueInput[]
  update?: Prisma.ShippingMethodUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.ShippingMethodUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.ShippingMethodUpdateManyWithWhereWithoutOrganizationInput | Prisma.ShippingMethodUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.ShippingMethodScalarWhereInput | Prisma.ShippingMethodScalarWhereInput[]
}

export type ShippingMethodUncheckedUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.ShippingMethodCreateWithoutOrganizationInput, Prisma.ShippingMethodUncheckedCreateWithoutOrganizationInput> | Prisma.ShippingMethodCreateWithoutOrganizationInput[] | Prisma.ShippingMethodUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.ShippingMethodCreateOrConnectWithoutOrganizationInput | Prisma.ShippingMethodCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.ShippingMethodUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.ShippingMethodUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.ShippingMethodCreateManyOrganizationInputEnvelope
  set?: Prisma.ShippingMethodWhereUniqueInput | Prisma.ShippingMethodWhereUniqueInput[]
  disconnect?: Prisma.ShippingMethodWhereUniqueInput | Prisma.ShippingMethodWhereUniqueInput[]
  delete?: Prisma.ShippingMethodWhereUniqueInput | Prisma.ShippingMethodWhereUniqueInput[]
  connect?: Prisma.ShippingMethodWhereUniqueInput | Prisma.ShippingMethodWhereUniqueInput[]
  update?: Prisma.ShippingMethodUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.ShippingMethodUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.ShippingMethodUpdateManyWithWhereWithoutOrganizationInput | Prisma.ShippingMethodUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.ShippingMethodScalarWhereInput | Prisma.ShippingMethodScalarWhereInput[]
}

export type ShippingMethodCreateNestedOneWithoutProviderLogoInput = {
  create?: Prisma.XOR<Prisma.ShippingMethodCreateWithoutProviderLogoInput, Prisma.ShippingMethodUncheckedCreateWithoutProviderLogoInput>
  connectOrCreate?: Prisma.ShippingMethodCreateOrConnectWithoutProviderLogoInput
  connect?: Prisma.ShippingMethodWhereUniqueInput
}

export type ShippingMethodUncheckedCreateNestedOneWithoutProviderLogoInput = {
  create?: Prisma.XOR<Prisma.ShippingMethodCreateWithoutProviderLogoInput, Prisma.ShippingMethodUncheckedCreateWithoutProviderLogoInput>
  connectOrCreate?: Prisma.ShippingMethodCreateOrConnectWithoutProviderLogoInput
  connect?: Prisma.ShippingMethodWhereUniqueInput
}

export type ShippingMethodUpdateOneWithoutProviderLogoNestedInput = {
  create?: Prisma.XOR<Prisma.ShippingMethodCreateWithoutProviderLogoInput, Prisma.ShippingMethodUncheckedCreateWithoutProviderLogoInput>
  connectOrCreate?: Prisma.ShippingMethodCreateOrConnectWithoutProviderLogoInput
  upsert?: Prisma.ShippingMethodUpsertWithoutProviderLogoInput
  disconnect?: Prisma.ShippingMethodWhereInput | boolean
  delete?: Prisma.ShippingMethodWhereInput | boolean
  connect?: Prisma.ShippingMethodWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ShippingMethodUpdateToOneWithWhereWithoutProviderLogoInput, Prisma.ShippingMethodUpdateWithoutProviderLogoInput>, Prisma.ShippingMethodUncheckedUpdateWithoutProviderLogoInput>
}

export type ShippingMethodUncheckedUpdateOneWithoutProviderLogoNestedInput = {
  create?: Prisma.XOR<Prisma.ShippingMethodCreateWithoutProviderLogoInput, Prisma.ShippingMethodUncheckedCreateWithoutProviderLogoInput>
  connectOrCreate?: Prisma.ShippingMethodCreateOrConnectWithoutProviderLogoInput
  upsert?: Prisma.ShippingMethodUpsertWithoutProviderLogoInput
  disconnect?: Prisma.ShippingMethodWhereInput | boolean
  delete?: Prisma.ShippingMethodWhereInput | boolean
  connect?: Prisma.ShippingMethodWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ShippingMethodUpdateToOneWithWhereWithoutProviderLogoInput, Prisma.ShippingMethodUpdateWithoutProviderLogoInput>, Prisma.ShippingMethodUncheckedUpdateWithoutProviderLogoInput>
}

export type ShippingMethodCreateNestedOneWithoutOrdersInput = {
  create?: Prisma.XOR<Prisma.ShippingMethodCreateWithoutOrdersInput, Prisma.ShippingMethodUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.ShippingMethodCreateOrConnectWithoutOrdersInput
  connect?: Prisma.ShippingMethodWhereUniqueInput
}

export type ShippingMethodUpdateOneWithoutOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.ShippingMethodCreateWithoutOrdersInput, Prisma.ShippingMethodUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.ShippingMethodCreateOrConnectWithoutOrdersInput
  upsert?: Prisma.ShippingMethodUpsertWithoutOrdersInput
  disconnect?: Prisma.ShippingMethodWhereInput | boolean
  delete?: Prisma.ShippingMethodWhereInput | boolean
  connect?: Prisma.ShippingMethodWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ShippingMethodUpdateToOneWithWhereWithoutOrdersInput, Prisma.ShippingMethodUpdateWithoutOrdersInput>, Prisma.ShippingMethodUncheckedUpdateWithoutOrdersInput>
}

export type ShippingMethodCreateNestedOneWithoutShippingZonesInput = {
  create?: Prisma.XOR<Prisma.ShippingMethodCreateWithoutShippingZonesInput, Prisma.ShippingMethodUncheckedCreateWithoutShippingZonesInput>
  connectOrCreate?: Prisma.ShippingMethodCreateOrConnectWithoutShippingZonesInput
  connect?: Prisma.ShippingMethodWhereUniqueInput
}

export type ShippingMethodUpdateOneRequiredWithoutShippingZonesNestedInput = {
  create?: Prisma.XOR<Prisma.ShippingMethodCreateWithoutShippingZonesInput, Prisma.ShippingMethodUncheckedCreateWithoutShippingZonesInput>
  connectOrCreate?: Prisma.ShippingMethodCreateOrConnectWithoutShippingZonesInput
  upsert?: Prisma.ShippingMethodUpsertWithoutShippingZonesInput
  connect?: Prisma.ShippingMethodWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ShippingMethodUpdateToOneWithWhereWithoutShippingZonesInput, Prisma.ShippingMethodUpdateWithoutShippingZonesInput>, Prisma.ShippingMethodUncheckedUpdateWithoutShippingZonesInput>
}

export type ShippingMethodCreateWithoutOrganizationInput = {
  id?: string
  title: string
  providerName: string
  requireDateOfDelivery?: boolean | null
  archivedAt?: Date | string | null
  archivedBy?: string | null
  publishedAt?: Date | string | null
  publishedBy?: string | null
  createdAt?: Date | string
  createdBy?: string | null
  updatedAt?: Date | string
  updatedBy?: string | null
  providerLogo?: Prisma.FileCreateNestedOneWithoutShippingMethodLogoForInput
  shippingZones?: Prisma.ShippingZoneCreateNestedManyWithoutShippingMethodInput
  orders?: Prisma.OrderCreateNestedManyWithoutShippingMethodInput
}

export type ShippingMethodUncheckedCreateWithoutOrganizationInput = {
  id?: string
  title: string
  providerName: string
  providerLogoId?: string | null
  requireDateOfDelivery?: boolean | null
  archivedAt?: Date | string | null
  archivedBy?: string | null
  publishedAt?: Date | string | null
  publishedBy?: string | null
  createdAt?: Date | string
  createdBy?: string | null
  updatedAt?: Date | string
  updatedBy?: string | null
  shippingZones?: Prisma.ShippingZoneUncheckedCreateNestedManyWithoutShippingMethodInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutShippingMethodInput
}

export type ShippingMethodCreateOrConnectWithoutOrganizationInput = {
  where: Prisma.ShippingMethodWhereUniqueInput
  create: Prisma.XOR<Prisma.ShippingMethodCreateWithoutOrganizationInput, Prisma.ShippingMethodUncheckedCreateWithoutOrganizationInput>
}

export type ShippingMethodCreateManyOrganizationInputEnvelope = {
  data: Prisma.ShippingMethodCreateManyOrganizationInput | Prisma.ShippingMethodCreateManyOrganizationInput[]
  skipDuplicates?: boolean
}

export type ShippingMethodUpsertWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.ShippingMethodWhereUniqueInput
  update: Prisma.XOR<Prisma.ShippingMethodUpdateWithoutOrganizationInput, Prisma.ShippingMethodUncheckedUpdateWithoutOrganizationInput>
  create: Prisma.XOR<Prisma.ShippingMethodCreateWithoutOrganizationInput, Prisma.ShippingMethodUncheckedCreateWithoutOrganizationInput>
}

export type ShippingMethodUpdateWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.ShippingMethodWhereUniqueInput
  data: Prisma.XOR<Prisma.ShippingMethodUpdateWithoutOrganizationInput, Prisma.ShippingMethodUncheckedUpdateWithoutOrganizationInput>
}

export type ShippingMethodUpdateManyWithWhereWithoutOrganizationInput = {
  where: Prisma.ShippingMethodScalarWhereInput
  data: Prisma.XOR<Prisma.ShippingMethodUpdateManyMutationInput, Prisma.ShippingMethodUncheckedUpdateManyWithoutOrganizationInput>
}

export type ShippingMethodScalarWhereInput = {
  AND?: Prisma.ShippingMethodScalarWhereInput | Prisma.ShippingMethodScalarWhereInput[]
  OR?: Prisma.ShippingMethodScalarWhereInput[]
  NOT?: Prisma.ShippingMethodScalarWhereInput | Prisma.ShippingMethodScalarWhereInput[]
  id?: Prisma.StringFilter<"ShippingMethod"> | string
  title?: Prisma.StringFilter<"ShippingMethod"> | string
  providerName?: Prisma.StringFilter<"ShippingMethod"> | string
  providerLogoId?: Prisma.StringNullableFilter<"ShippingMethod"> | string | null
  requireDateOfDelivery?: Prisma.BoolNullableFilter<"ShippingMethod"> | boolean | null
  organizationId?: Prisma.StringFilter<"ShippingMethod"> | string
  archivedAt?: Prisma.DateTimeNullableFilter<"ShippingMethod"> | Date | string | null
  archivedBy?: Prisma.StringNullableFilter<"ShippingMethod"> | string | null
  publishedAt?: Prisma.DateTimeNullableFilter<"ShippingMethod"> | Date | string | null
  publishedBy?: Prisma.StringNullableFilter<"ShippingMethod"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ShippingMethod"> | Date | string
  createdBy?: Prisma.StringNullableFilter<"ShippingMethod"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"ShippingMethod"> | Date | string
  updatedBy?: Prisma.StringNullableFilter<"ShippingMethod"> | string | null
}

export type ShippingMethodCreateWithoutProviderLogoInput = {
  id?: string
  title: string
  providerName: string
  requireDateOfDelivery?: boolean | null
  archivedAt?: Date | string | null
  archivedBy?: string | null
  publishedAt?: Date | string | null
  publishedBy?: string | null
  createdAt?: Date | string
  createdBy?: string | null
  updatedAt?: Date | string
  updatedBy?: string | null
  organization: Prisma.OrganizationCreateNestedOneWithoutShippingMethodsInput
  shippingZones?: Prisma.ShippingZoneCreateNestedManyWithoutShippingMethodInput
  orders?: Prisma.OrderCreateNestedManyWithoutShippingMethodInput
}

export type ShippingMethodUncheckedCreateWithoutProviderLogoInput = {
  id?: string
  title: string
  providerName: string
  requireDateOfDelivery?: boolean | null
  organizationId: string
  archivedAt?: Date | string | null
  archivedBy?: string | null
  publishedAt?: Date | string | null
  publishedBy?: string | null
  createdAt?: Date | string
  createdBy?: string | null
  updatedAt?: Date | string
  updatedBy?: string | null
  shippingZones?: Prisma.ShippingZoneUncheckedCreateNestedManyWithoutShippingMethodInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutShippingMethodInput
}

export type ShippingMethodCreateOrConnectWithoutProviderLogoInput = {
  where: Prisma.ShippingMethodWhereUniqueInput
  create: Prisma.XOR<Prisma.ShippingMethodCreateWithoutProviderLogoInput, Prisma.ShippingMethodUncheckedCreateWithoutProviderLogoInput>
}

export type ShippingMethodUpsertWithoutProviderLogoInput = {
  update: Prisma.XOR<Prisma.ShippingMethodUpdateWithoutProviderLogoInput, Prisma.ShippingMethodUncheckedUpdateWithoutProviderLogoInput>
  create: Prisma.XOR<Prisma.ShippingMethodCreateWithoutProviderLogoInput, Prisma.ShippingMethodUncheckedCreateWithoutProviderLogoInput>
  where?: Prisma.ShippingMethodWhereInput
}

export type ShippingMethodUpdateToOneWithWhereWithoutProviderLogoInput = {
  where?: Prisma.ShippingMethodWhereInput
  data: Prisma.XOR<Prisma.ShippingMethodUpdateWithoutProviderLogoInput, Prisma.ShippingMethodUncheckedUpdateWithoutProviderLogoInput>
}

export type ShippingMethodUpdateWithoutProviderLogoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  providerName?: Prisma.StringFieldUpdateOperationsInput | string
  requireDateOfDelivery?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archivedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  archivedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutShippingMethodsNestedInput
  shippingZones?: Prisma.ShippingZoneUpdateManyWithoutShippingMethodNestedInput
  orders?: Prisma.OrderUpdateManyWithoutShippingMethodNestedInput
}

export type ShippingMethodUncheckedUpdateWithoutProviderLogoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  providerName?: Prisma.StringFieldUpdateOperationsInput | string
  requireDateOfDelivery?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  archivedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  archivedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingZones?: Prisma.ShippingZoneUncheckedUpdateManyWithoutShippingMethodNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutShippingMethodNestedInput
}

export type ShippingMethodCreateWithoutOrdersInput = {
  id?: string
  title: string
  providerName: string
  requireDateOfDelivery?: boolean | null
  archivedAt?: Date | string | null
  archivedBy?: string | null
  publishedAt?: Date | string | null
  publishedBy?: string | null
  createdAt?: Date | string
  createdBy?: string | null
  updatedAt?: Date | string
  updatedBy?: string | null
  providerLogo?: Prisma.FileCreateNestedOneWithoutShippingMethodLogoForInput
  organization: Prisma.OrganizationCreateNestedOneWithoutShippingMethodsInput
  shippingZones?: Prisma.ShippingZoneCreateNestedManyWithoutShippingMethodInput
}

export type ShippingMethodUncheckedCreateWithoutOrdersInput = {
  id?: string
  title: string
  providerName: string
  providerLogoId?: string | null
  requireDateOfDelivery?: boolean | null
  organizationId: string
  archivedAt?: Date | string | null
  archivedBy?: string | null
  publishedAt?: Date | string | null
  publishedBy?: string | null
  createdAt?: Date | string
  createdBy?: string | null
  updatedAt?: Date | string
  updatedBy?: string | null
  shippingZones?: Prisma.ShippingZoneUncheckedCreateNestedManyWithoutShippingMethodInput
}

export type ShippingMethodCreateOrConnectWithoutOrdersInput = {
  where: Prisma.ShippingMethodWhereUniqueInput
  create: Prisma.XOR<Prisma.ShippingMethodCreateWithoutOrdersInput, Prisma.ShippingMethodUncheckedCreateWithoutOrdersInput>
}

export type ShippingMethodUpsertWithoutOrdersInput = {
  update: Prisma.XOR<Prisma.ShippingMethodUpdateWithoutOrdersInput, Prisma.ShippingMethodUncheckedUpdateWithoutOrdersInput>
  create: Prisma.XOR<Prisma.ShippingMethodCreateWithoutOrdersInput, Prisma.ShippingMethodUncheckedCreateWithoutOrdersInput>
  where?: Prisma.ShippingMethodWhereInput
}

export type ShippingMethodUpdateToOneWithWhereWithoutOrdersInput = {
  where?: Prisma.ShippingMethodWhereInput
  data: Prisma.XOR<Prisma.ShippingMethodUpdateWithoutOrdersInput, Prisma.ShippingMethodUncheckedUpdateWithoutOrdersInput>
}

export type ShippingMethodUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  providerName?: Prisma.StringFieldUpdateOperationsInput | string
  requireDateOfDelivery?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archivedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  archivedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  providerLogo?: Prisma.FileUpdateOneWithoutShippingMethodLogoForNestedInput
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutShippingMethodsNestedInput
  shippingZones?: Prisma.ShippingZoneUpdateManyWithoutShippingMethodNestedInput
}

export type ShippingMethodUncheckedUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  providerName?: Prisma.StringFieldUpdateOperationsInput | string
  providerLogoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requireDateOfDelivery?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  archivedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  archivedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingZones?: Prisma.ShippingZoneUncheckedUpdateManyWithoutShippingMethodNestedInput
}

export type ShippingMethodCreateWithoutShippingZonesInput = {
  id?: string
  title: string
  providerName: string
  requireDateOfDelivery?: boolean | null
  archivedAt?: Date | string | null
  archivedBy?: string | null
  publishedAt?: Date | string | null
  publishedBy?: string | null
  createdAt?: Date | string
  createdBy?: string | null
  updatedAt?: Date | string
  updatedBy?: string | null
  providerLogo?: Prisma.FileCreateNestedOneWithoutShippingMethodLogoForInput
  organization: Prisma.OrganizationCreateNestedOneWithoutShippingMethodsInput
  orders?: Prisma.OrderCreateNestedManyWithoutShippingMethodInput
}

export type ShippingMethodUncheckedCreateWithoutShippingZonesInput = {
  id?: string
  title: string
  providerName: string
  providerLogoId?: string | null
  requireDateOfDelivery?: boolean | null
  organizationId: string
  archivedAt?: Date | string | null
  archivedBy?: string | null
  publishedAt?: Date | string | null
  publishedBy?: string | null
  createdAt?: Date | string
  createdBy?: string | null
  updatedAt?: Date | string
  updatedBy?: string | null
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutShippingMethodInput
}

export type ShippingMethodCreateOrConnectWithoutShippingZonesInput = {
  where: Prisma.ShippingMethodWhereUniqueInput
  create: Prisma.XOR<Prisma.ShippingMethodCreateWithoutShippingZonesInput, Prisma.ShippingMethodUncheckedCreateWithoutShippingZonesInput>
}

export type ShippingMethodUpsertWithoutShippingZonesInput = {
  update: Prisma.XOR<Prisma.ShippingMethodUpdateWithoutShippingZonesInput, Prisma.ShippingMethodUncheckedUpdateWithoutShippingZonesInput>
  create: Prisma.XOR<Prisma.ShippingMethodCreateWithoutShippingZonesInput, Prisma.ShippingMethodUncheckedCreateWithoutShippingZonesInput>
  where?: Prisma.ShippingMethodWhereInput
}

export type ShippingMethodUpdateToOneWithWhereWithoutShippingZonesInput = {
  where?: Prisma.ShippingMethodWhereInput
  data: Prisma.XOR<Prisma.ShippingMethodUpdateWithoutShippingZonesInput, Prisma.ShippingMethodUncheckedUpdateWithoutShippingZonesInput>
}

export type ShippingMethodUpdateWithoutShippingZonesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  providerName?: Prisma.StringFieldUpdateOperationsInput | string
  requireDateOfDelivery?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archivedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  archivedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  providerLogo?: Prisma.FileUpdateOneWithoutShippingMethodLogoForNestedInput
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutShippingMethodsNestedInput
  orders?: Prisma.OrderUpdateManyWithoutShippingMethodNestedInput
}

export type ShippingMethodUncheckedUpdateWithoutShippingZonesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  providerName?: Prisma.StringFieldUpdateOperationsInput | string
  providerLogoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requireDateOfDelivery?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  archivedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  archivedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  orders?: Prisma.OrderUncheckedUpdateManyWithoutShippingMethodNestedInput
}

export type ShippingMethodCreateManyOrganizationInput = {
  id?: string
  title: string
  providerName: string
  providerLogoId?: string | null
  requireDateOfDelivery?: boolean | null
  archivedAt?: Date | string | null
  archivedBy?: string | null
  publishedAt?: Date | string | null
  publishedBy?: string | null
  createdAt?: Date | string
  createdBy?: string | null
  updatedAt?: Date | string
  updatedBy?: string | null
}

export type ShippingMethodUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  providerName?: Prisma.StringFieldUpdateOperationsInput | string
  requireDateOfDelivery?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archivedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  archivedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  providerLogo?: Prisma.FileUpdateOneWithoutShippingMethodLogoForNestedInput
  shippingZones?: Prisma.ShippingZoneUpdateManyWithoutShippingMethodNestedInput
  orders?: Prisma.OrderUpdateManyWithoutShippingMethodNestedInput
}

export type ShippingMethodUncheckedUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  providerName?: Prisma.StringFieldUpdateOperationsInput | string
  providerLogoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requireDateOfDelivery?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archivedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  archivedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingZones?: Prisma.ShippingZoneUncheckedUpdateManyWithoutShippingMethodNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutShippingMethodNestedInput
}

export type ShippingMethodUncheckedUpdateManyWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  providerName?: Prisma.StringFieldUpdateOperationsInput | string
  providerLogoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requireDateOfDelivery?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  archivedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  archivedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type ShippingMethodCountOutputType
 */

export type ShippingMethodCountOutputType = {
  shippingZones: number
  orders: number
}

export type ShippingMethodCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  shippingZones?: boolean | ShippingMethodCountOutputTypeCountShippingZonesArgs
  orders?: boolean | ShippingMethodCountOutputTypeCountOrdersArgs
}

/**
 * ShippingMethodCountOutputType without action
 */
export type ShippingMethodCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShippingMethodCountOutputType
   */
  select?: Prisma.ShippingMethodCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ShippingMethodCountOutputType without action
 */
export type ShippingMethodCountOutputTypeCountShippingZonesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ShippingZoneWhereInput
}

/**
 * ShippingMethodCountOutputType without action
 */
export type ShippingMethodCountOutputTypeCountOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderWhereInput
}


export type ShippingMethodSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  providerName?: boolean
  providerLogoId?: boolean
  requireDateOfDelivery?: boolean
  organizationId?: boolean
  archivedAt?: boolean
  archivedBy?: boolean
  publishedAt?: boolean
  publishedBy?: boolean
  createdAt?: boolean
  createdBy?: boolean
  updatedAt?: boolean
  updatedBy?: boolean
  providerLogo?: boolean | Prisma.ShippingMethod$providerLogoArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  shippingZones?: boolean | Prisma.ShippingMethod$shippingZonesArgs<ExtArgs>
  orders?: boolean | Prisma.ShippingMethod$ordersArgs<ExtArgs>
  _count?: boolean | Prisma.ShippingMethodCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["shippingMethod"]>

export type ShippingMethodSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  providerName?: boolean
  providerLogoId?: boolean
  requireDateOfDelivery?: boolean
  organizationId?: boolean
  archivedAt?: boolean
  archivedBy?: boolean
  publishedAt?: boolean
  publishedBy?: boolean
  createdAt?: boolean
  createdBy?: boolean
  updatedAt?: boolean
  updatedBy?: boolean
  providerLogo?: boolean | Prisma.ShippingMethod$providerLogoArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["shippingMethod"]>

export type ShippingMethodSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  providerName?: boolean
  providerLogoId?: boolean
  requireDateOfDelivery?: boolean
  organizationId?: boolean
  archivedAt?: boolean
  archivedBy?: boolean
  publishedAt?: boolean
  publishedBy?: boolean
  createdAt?: boolean
  createdBy?: boolean
  updatedAt?: boolean
  updatedBy?: boolean
  providerLogo?: boolean | Prisma.ShippingMethod$providerLogoArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["shippingMethod"]>

export type ShippingMethodSelectScalar = {
  id?: boolean
  title?: boolean
  providerName?: boolean
  providerLogoId?: boolean
  requireDateOfDelivery?: boolean
  organizationId?: boolean
  archivedAt?: boolean
  archivedBy?: boolean
  publishedAt?: boolean
  publishedBy?: boolean
  createdAt?: boolean
  createdBy?: boolean
  updatedAt?: boolean
  updatedBy?: boolean
}

export type ShippingMethodOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "providerName" | "providerLogoId" | "requireDateOfDelivery" | "organizationId" | "archivedAt" | "archivedBy" | "publishedAt" | "publishedBy" | "createdAt" | "createdBy" | "updatedAt" | "updatedBy", ExtArgs["result"]["shippingMethod"]>
export type ShippingMethodInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  providerLogo?: boolean | Prisma.ShippingMethod$providerLogoArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  shippingZones?: boolean | Prisma.ShippingMethod$shippingZonesArgs<ExtArgs>
  orders?: boolean | Prisma.ShippingMethod$ordersArgs<ExtArgs>
  _count?: boolean | Prisma.ShippingMethodCountOutputTypeDefaultArgs<ExtArgs>
}
export type ShippingMethodIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  providerLogo?: boolean | Prisma.ShippingMethod$providerLogoArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}
export type ShippingMethodIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  providerLogo?: boolean | Prisma.ShippingMethod$providerLogoArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}

export type $ShippingMethodPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ShippingMethod"
  objects: {
    providerLogo: Prisma.$FilePayload<ExtArgs> | null
    organization: Prisma.$OrganizationPayload<ExtArgs>
    shippingZones: Prisma.$ShippingZonePayload<ExtArgs>[]
    orders: Prisma.$OrderPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    providerName: string
    providerLogoId: string | null
    requireDateOfDelivery: boolean | null
    organizationId: string
    archivedAt: Date | null
    archivedBy: string | null
    publishedAt: Date | null
    publishedBy: string | null
    createdAt: Date
    createdBy: string | null
    updatedAt: Date
    updatedBy: string | null
  }, ExtArgs["result"]["shippingMethod"]>
  composites: {}
}

export type ShippingMethodGetPayload<S extends boolean | null | undefined | ShippingMethodDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ShippingMethodPayload, S>

export type ShippingMethodCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ShippingMethodFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ShippingMethodCountAggregateInputType | true
  }

export interface ShippingMethodDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ShippingMethod'], meta: { name: 'ShippingMethod' } }
  /**
   * Find zero or one ShippingMethod that matches the filter.
   * @param {ShippingMethodFindUniqueArgs} args - Arguments to find a ShippingMethod
   * @example
   * // Get one ShippingMethod
   * const shippingMethod = await prisma.shippingMethod.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ShippingMethodFindUniqueArgs>(args: Prisma.SelectSubset<T, ShippingMethodFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ShippingMethodClient<runtime.Types.Result.GetResult<Prisma.$ShippingMethodPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ShippingMethod that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ShippingMethodFindUniqueOrThrowArgs} args - Arguments to find a ShippingMethod
   * @example
   * // Get one ShippingMethod
   * const shippingMethod = await prisma.shippingMethod.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ShippingMethodFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ShippingMethodFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ShippingMethodClient<runtime.Types.Result.GetResult<Prisma.$ShippingMethodPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ShippingMethod that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShippingMethodFindFirstArgs} args - Arguments to find a ShippingMethod
   * @example
   * // Get one ShippingMethod
   * const shippingMethod = await prisma.shippingMethod.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ShippingMethodFindFirstArgs>(args?: Prisma.SelectSubset<T, ShippingMethodFindFirstArgs<ExtArgs>>): Prisma.Prisma__ShippingMethodClient<runtime.Types.Result.GetResult<Prisma.$ShippingMethodPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ShippingMethod that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShippingMethodFindFirstOrThrowArgs} args - Arguments to find a ShippingMethod
   * @example
   * // Get one ShippingMethod
   * const shippingMethod = await prisma.shippingMethod.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ShippingMethodFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ShippingMethodFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ShippingMethodClient<runtime.Types.Result.GetResult<Prisma.$ShippingMethodPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ShippingMethods that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShippingMethodFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ShippingMethods
   * const shippingMethods = await prisma.shippingMethod.findMany()
   * 
   * // Get first 10 ShippingMethods
   * const shippingMethods = await prisma.shippingMethod.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const shippingMethodWithIdOnly = await prisma.shippingMethod.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ShippingMethodFindManyArgs>(args?: Prisma.SelectSubset<T, ShippingMethodFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShippingMethodPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ShippingMethod.
   * @param {ShippingMethodCreateArgs} args - Arguments to create a ShippingMethod.
   * @example
   * // Create one ShippingMethod
   * const ShippingMethod = await prisma.shippingMethod.create({
   *   data: {
   *     // ... data to create a ShippingMethod
   *   }
   * })
   * 
   */
  create<T extends ShippingMethodCreateArgs>(args: Prisma.SelectSubset<T, ShippingMethodCreateArgs<ExtArgs>>): Prisma.Prisma__ShippingMethodClient<runtime.Types.Result.GetResult<Prisma.$ShippingMethodPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ShippingMethods.
   * @param {ShippingMethodCreateManyArgs} args - Arguments to create many ShippingMethods.
   * @example
   * // Create many ShippingMethods
   * const shippingMethod = await prisma.shippingMethod.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ShippingMethodCreateManyArgs>(args?: Prisma.SelectSubset<T, ShippingMethodCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ShippingMethods and returns the data saved in the database.
   * @param {ShippingMethodCreateManyAndReturnArgs} args - Arguments to create many ShippingMethods.
   * @example
   * // Create many ShippingMethods
   * const shippingMethod = await prisma.shippingMethod.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ShippingMethods and only return the `id`
   * const shippingMethodWithIdOnly = await prisma.shippingMethod.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ShippingMethodCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ShippingMethodCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShippingMethodPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ShippingMethod.
   * @param {ShippingMethodDeleteArgs} args - Arguments to delete one ShippingMethod.
   * @example
   * // Delete one ShippingMethod
   * const ShippingMethod = await prisma.shippingMethod.delete({
   *   where: {
   *     // ... filter to delete one ShippingMethod
   *   }
   * })
   * 
   */
  delete<T extends ShippingMethodDeleteArgs>(args: Prisma.SelectSubset<T, ShippingMethodDeleteArgs<ExtArgs>>): Prisma.Prisma__ShippingMethodClient<runtime.Types.Result.GetResult<Prisma.$ShippingMethodPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ShippingMethod.
   * @param {ShippingMethodUpdateArgs} args - Arguments to update one ShippingMethod.
   * @example
   * // Update one ShippingMethod
   * const shippingMethod = await prisma.shippingMethod.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ShippingMethodUpdateArgs>(args: Prisma.SelectSubset<T, ShippingMethodUpdateArgs<ExtArgs>>): Prisma.Prisma__ShippingMethodClient<runtime.Types.Result.GetResult<Prisma.$ShippingMethodPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ShippingMethods.
   * @param {ShippingMethodDeleteManyArgs} args - Arguments to filter ShippingMethods to delete.
   * @example
   * // Delete a few ShippingMethods
   * const { count } = await prisma.shippingMethod.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ShippingMethodDeleteManyArgs>(args?: Prisma.SelectSubset<T, ShippingMethodDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ShippingMethods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShippingMethodUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ShippingMethods
   * const shippingMethod = await prisma.shippingMethod.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ShippingMethodUpdateManyArgs>(args: Prisma.SelectSubset<T, ShippingMethodUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ShippingMethods and returns the data updated in the database.
   * @param {ShippingMethodUpdateManyAndReturnArgs} args - Arguments to update many ShippingMethods.
   * @example
   * // Update many ShippingMethods
   * const shippingMethod = await prisma.shippingMethod.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ShippingMethods and only return the `id`
   * const shippingMethodWithIdOnly = await prisma.shippingMethod.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ShippingMethodUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ShippingMethodUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShippingMethodPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ShippingMethod.
   * @param {ShippingMethodUpsertArgs} args - Arguments to update or create a ShippingMethod.
   * @example
   * // Update or create a ShippingMethod
   * const shippingMethod = await prisma.shippingMethod.upsert({
   *   create: {
   *     // ... data to create a ShippingMethod
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ShippingMethod we want to update
   *   }
   * })
   */
  upsert<T extends ShippingMethodUpsertArgs>(args: Prisma.SelectSubset<T, ShippingMethodUpsertArgs<ExtArgs>>): Prisma.Prisma__ShippingMethodClient<runtime.Types.Result.GetResult<Prisma.$ShippingMethodPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ShippingMethods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShippingMethodCountArgs} args - Arguments to filter ShippingMethods to count.
   * @example
   * // Count the number of ShippingMethods
   * const count = await prisma.shippingMethod.count({
   *   where: {
   *     // ... the filter for the ShippingMethods we want to count
   *   }
   * })
  **/
  count<T extends ShippingMethodCountArgs>(
    args?: Prisma.Subset<T, ShippingMethodCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ShippingMethodCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ShippingMethod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShippingMethodAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ShippingMethodAggregateArgs>(args: Prisma.Subset<T, ShippingMethodAggregateArgs>): Prisma.PrismaPromise<GetShippingMethodAggregateType<T>>

  /**
   * Group by ShippingMethod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShippingMethodGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ShippingMethodGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ShippingMethodGroupByArgs['orderBy'] }
      : { orderBy?: ShippingMethodGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ShippingMethodGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetShippingMethodGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ShippingMethod model
 */
readonly fields: ShippingMethodFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ShippingMethod.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ShippingMethodClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  providerLogo<T extends Prisma.ShippingMethod$providerLogoArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ShippingMethod$providerLogoArgs<ExtArgs>>): Prisma.Prisma__FileClient<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  organization<T extends Prisma.OrganizationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrganizationDefaultArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  shippingZones<T extends Prisma.ShippingMethod$shippingZonesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ShippingMethod$shippingZonesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShippingZonePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  orders<T extends Prisma.ShippingMethod$ordersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ShippingMethod$ordersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ShippingMethod model
 */
export interface ShippingMethodFieldRefs {
  readonly id: Prisma.FieldRef<"ShippingMethod", 'String'>
  readonly title: Prisma.FieldRef<"ShippingMethod", 'String'>
  readonly providerName: Prisma.FieldRef<"ShippingMethod", 'String'>
  readonly providerLogoId: Prisma.FieldRef<"ShippingMethod", 'String'>
  readonly requireDateOfDelivery: Prisma.FieldRef<"ShippingMethod", 'Boolean'>
  readonly organizationId: Prisma.FieldRef<"ShippingMethod", 'String'>
  readonly archivedAt: Prisma.FieldRef<"ShippingMethod", 'DateTime'>
  readonly archivedBy: Prisma.FieldRef<"ShippingMethod", 'String'>
  readonly publishedAt: Prisma.FieldRef<"ShippingMethod", 'DateTime'>
  readonly publishedBy: Prisma.FieldRef<"ShippingMethod", 'String'>
  readonly createdAt: Prisma.FieldRef<"ShippingMethod", 'DateTime'>
  readonly createdBy: Prisma.FieldRef<"ShippingMethod", 'String'>
  readonly updatedAt: Prisma.FieldRef<"ShippingMethod", 'DateTime'>
  readonly updatedBy: Prisma.FieldRef<"ShippingMethod", 'String'>
}
    

// Custom InputTypes
/**
 * ShippingMethod findUnique
 */
export type ShippingMethodFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShippingMethod
   */
  select?: Prisma.ShippingMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShippingMethod
   */
  omit?: Prisma.ShippingMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShippingMethodInclude<ExtArgs> | null
  /**
   * Filter, which ShippingMethod to fetch.
   */
  where: Prisma.ShippingMethodWhereUniqueInput
}

/**
 * ShippingMethod findUniqueOrThrow
 */
export type ShippingMethodFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShippingMethod
   */
  select?: Prisma.ShippingMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShippingMethod
   */
  omit?: Prisma.ShippingMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShippingMethodInclude<ExtArgs> | null
  /**
   * Filter, which ShippingMethod to fetch.
   */
  where: Prisma.ShippingMethodWhereUniqueInput
}

/**
 * ShippingMethod findFirst
 */
export type ShippingMethodFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShippingMethod
   */
  select?: Prisma.ShippingMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShippingMethod
   */
  omit?: Prisma.ShippingMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShippingMethodInclude<ExtArgs> | null
  /**
   * Filter, which ShippingMethod to fetch.
   */
  where?: Prisma.ShippingMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShippingMethods to fetch.
   */
  orderBy?: Prisma.ShippingMethodOrderByWithRelationInput | Prisma.ShippingMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ShippingMethods.
   */
  cursor?: Prisma.ShippingMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShippingMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShippingMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ShippingMethods.
   */
  distinct?: Prisma.ShippingMethodScalarFieldEnum | Prisma.ShippingMethodScalarFieldEnum[]
}

/**
 * ShippingMethod findFirstOrThrow
 */
export type ShippingMethodFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShippingMethod
   */
  select?: Prisma.ShippingMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShippingMethod
   */
  omit?: Prisma.ShippingMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShippingMethodInclude<ExtArgs> | null
  /**
   * Filter, which ShippingMethod to fetch.
   */
  where?: Prisma.ShippingMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShippingMethods to fetch.
   */
  orderBy?: Prisma.ShippingMethodOrderByWithRelationInput | Prisma.ShippingMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ShippingMethods.
   */
  cursor?: Prisma.ShippingMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShippingMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShippingMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ShippingMethods.
   */
  distinct?: Prisma.ShippingMethodScalarFieldEnum | Prisma.ShippingMethodScalarFieldEnum[]
}

/**
 * ShippingMethod findMany
 */
export type ShippingMethodFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShippingMethod
   */
  select?: Prisma.ShippingMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShippingMethod
   */
  omit?: Prisma.ShippingMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShippingMethodInclude<ExtArgs> | null
  /**
   * Filter, which ShippingMethods to fetch.
   */
  where?: Prisma.ShippingMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShippingMethods to fetch.
   */
  orderBy?: Prisma.ShippingMethodOrderByWithRelationInput | Prisma.ShippingMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ShippingMethods.
   */
  cursor?: Prisma.ShippingMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShippingMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShippingMethods.
   */
  skip?: number
  distinct?: Prisma.ShippingMethodScalarFieldEnum | Prisma.ShippingMethodScalarFieldEnum[]
}

/**
 * ShippingMethod create
 */
export type ShippingMethodCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShippingMethod
   */
  select?: Prisma.ShippingMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShippingMethod
   */
  omit?: Prisma.ShippingMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShippingMethodInclude<ExtArgs> | null
  /**
   * The data needed to create a ShippingMethod.
   */
  data: Prisma.XOR<Prisma.ShippingMethodCreateInput, Prisma.ShippingMethodUncheckedCreateInput>
}

/**
 * ShippingMethod createMany
 */
export type ShippingMethodCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ShippingMethods.
   */
  data: Prisma.ShippingMethodCreateManyInput | Prisma.ShippingMethodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ShippingMethod createManyAndReturn
 */
export type ShippingMethodCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShippingMethod
   */
  select?: Prisma.ShippingMethodSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ShippingMethod
   */
  omit?: Prisma.ShippingMethodOmit<ExtArgs> | null
  /**
   * The data used to create many ShippingMethods.
   */
  data: Prisma.ShippingMethodCreateManyInput | Prisma.ShippingMethodCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShippingMethodIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ShippingMethod update
 */
export type ShippingMethodUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShippingMethod
   */
  select?: Prisma.ShippingMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShippingMethod
   */
  omit?: Prisma.ShippingMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShippingMethodInclude<ExtArgs> | null
  /**
   * The data needed to update a ShippingMethod.
   */
  data: Prisma.XOR<Prisma.ShippingMethodUpdateInput, Prisma.ShippingMethodUncheckedUpdateInput>
  /**
   * Choose, which ShippingMethod to update.
   */
  where: Prisma.ShippingMethodWhereUniqueInput
}

/**
 * ShippingMethod updateMany
 */
export type ShippingMethodUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ShippingMethods.
   */
  data: Prisma.XOR<Prisma.ShippingMethodUpdateManyMutationInput, Prisma.ShippingMethodUncheckedUpdateManyInput>
  /**
   * Filter which ShippingMethods to update
   */
  where?: Prisma.ShippingMethodWhereInput
  /**
   * Limit how many ShippingMethods to update.
   */
  limit?: number
}

/**
 * ShippingMethod updateManyAndReturn
 */
export type ShippingMethodUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShippingMethod
   */
  select?: Prisma.ShippingMethodSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ShippingMethod
   */
  omit?: Prisma.ShippingMethodOmit<ExtArgs> | null
  /**
   * The data used to update ShippingMethods.
   */
  data: Prisma.XOR<Prisma.ShippingMethodUpdateManyMutationInput, Prisma.ShippingMethodUncheckedUpdateManyInput>
  /**
   * Filter which ShippingMethods to update
   */
  where?: Prisma.ShippingMethodWhereInput
  /**
   * Limit how many ShippingMethods to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShippingMethodIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ShippingMethod upsert
 */
export type ShippingMethodUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShippingMethod
   */
  select?: Prisma.ShippingMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShippingMethod
   */
  omit?: Prisma.ShippingMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShippingMethodInclude<ExtArgs> | null
  /**
   * The filter to search for the ShippingMethod to update in case it exists.
   */
  where: Prisma.ShippingMethodWhereUniqueInput
  /**
   * In case the ShippingMethod found by the `where` argument doesn't exist, create a new ShippingMethod with this data.
   */
  create: Prisma.XOR<Prisma.ShippingMethodCreateInput, Prisma.ShippingMethodUncheckedCreateInput>
  /**
   * In case the ShippingMethod was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ShippingMethodUpdateInput, Prisma.ShippingMethodUncheckedUpdateInput>
}

/**
 * ShippingMethod delete
 */
export type ShippingMethodDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShippingMethod
   */
  select?: Prisma.ShippingMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShippingMethod
   */
  omit?: Prisma.ShippingMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShippingMethodInclude<ExtArgs> | null
  /**
   * Filter which ShippingMethod to delete.
   */
  where: Prisma.ShippingMethodWhereUniqueInput
}

/**
 * ShippingMethod deleteMany
 */
export type ShippingMethodDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ShippingMethods to delete
   */
  where?: Prisma.ShippingMethodWhereInput
  /**
   * Limit how many ShippingMethods to delete.
   */
  limit?: number
}

/**
 * ShippingMethod.providerLogo
 */
export type ShippingMethod$providerLogoArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  where?: Prisma.FileWhereInput
}

/**
 * ShippingMethod.shippingZones
 */
export type ShippingMethod$shippingZonesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShippingZone
   */
  select?: Prisma.ShippingZoneSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShippingZone
   */
  omit?: Prisma.ShippingZoneOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShippingZoneInclude<ExtArgs> | null
  where?: Prisma.ShippingZoneWhereInput
  orderBy?: Prisma.ShippingZoneOrderByWithRelationInput | Prisma.ShippingZoneOrderByWithRelationInput[]
  cursor?: Prisma.ShippingZoneWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ShippingZoneScalarFieldEnum | Prisma.ShippingZoneScalarFieldEnum[]
}

/**
 * ShippingMethod.orders
 */
export type ShippingMethod$ordersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  where?: Prisma.OrderWhereInput
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  cursor?: Prisma.OrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * ShippingMethod without action
 */
export type ShippingMethodDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShippingMethod
   */
  select?: Prisma.ShippingMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShippingMethod
   */
  omit?: Prisma.ShippingMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShippingMethodInclude<ExtArgs> | null
}
