
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/
export const FileUploadStatus = {
  pending: 'pending',
  completed: 'completed',
  failed: 'failed'
} as const

export type FileUploadStatus = (typeof FileUploadStatus)[keyof typeof FileUploadStatus]


export const Locale = {
  af: 'af',
  sq: 'sq',
  ar_dz: 'ar_dz',
  ar_bh: 'ar_bh',
  ar_eg: 'ar_eg',
  ar_iq: 'ar_iq',
  ar_jo: 'ar_jo',
  ar_kw: 'ar_kw',
  ar_lb: 'ar_lb',
  ar_ly: 'ar_ly',
  ar_ma: 'ar_ma',
  ar_om: 'ar_om',
  ar_qa: 'ar_qa',
  ar_sa: 'ar_sa',
  ar_sy: 'ar_sy',
  ar_tn: 'ar_tn',
  ar_ae: 'ar_ae',
  ar_ye: 'ar_ye',
  eu: 'eu',
  be: 'be',
  bg: 'bg',
  ca: 'ca',
  zh_hk: 'zh_hk',
  zh_cn: 'zh_cn',
  zh_sg: 'zh_sg',
  zh_tw: 'zh_tw',
  hr: 'hr',
  cs: 'cs',
  da: 'da',
  nl_be: 'nl_be',
  nl: 'nl',
  en: 'en',
  en_au: 'en_au',
  en_bz: 'en_bz',
  en_ca: 'en_ca',
  en_ie: 'en_ie',
  en_jm: 'en_jm',
  en_nz: 'en_nz',
  en_za: 'en_za',
  en_tt: 'en_tt',
  en_gb: 'en_gb',
  en_us: 'en_us',
  et: 'et',
  fo: 'fo',
  fa: 'fa',
  fi: 'fi',
  fr_be: 'fr_be',
  fr_ca: 'fr_ca',
  fr_lu: 'fr_lu',
  fr: 'fr',
  fr_ch: 'fr_ch',
  gd: 'gd',
  de_at: 'de_at',
  de_li: 'de_li',
  de_lu: 'de_lu',
  de: 'de',
  de_ch: 'de_ch',
  el: 'el',
  he: 'he',
  hi: 'hi',
  hu: 'hu',
  is: 'is',
  id: 'id',
  ga: 'ga',
  it: 'it',
  it_ch: 'it_ch',
  ja: 'ja',
  ko: 'ko',
  ku: 'ku',
  lv: 'lv',
  lt: 'lt',
  mk: 'mk',
  ml: 'ml',
  ms: 'ms',
  mt: 'mt',
  no: 'no',
  nb: 'nb',
  nn: 'nn',
  pl: 'pl',
  pt_br: 'pt_br',
  pt: 'pt',
  pa: 'pa',
  rm: 'rm',
  ro: 'ro',
  ro_md: 'ro_md',
  ru: 'ru',
  ru_md: 'ru_md',
  sr: 'sr',
  sk: 'sk',
  sl: 'sl',
  sb: 'sb',
  es_ar: 'es_ar',
  es_bo: 'es_bo',
  es_cl: 'es_cl',
  es_co: 'es_co',
  es_cr: 'es_cr',
  es_do: 'es_do',
  es_ec: 'es_ec',
  es_sv: 'es_sv',
  es_gt: 'es_gt',
  es_hn: 'es_hn',
  es_mx: 'es_mx',
  es: 'es',
  sv: 'sv',
  sv_fi: 'sv_fi',
  th: 'th',
  tr: 'tr',
  uk: 'uk',
  ur: 'ur',
  vi: 'vi',
  cy: 'cy',
  ji: 'ji',
  zu: 'zu'
} as const

export type Locale = (typeof Locale)[keyof typeof Locale]


export const Currency = {
  USD: 'USD',
  EUR: 'EUR',
  GBP: 'GBP',
  JPY: 'JPY',
  AUD: 'AUD',
  CAD: 'CAD',
  CHF: 'CHF',
  CNY: 'CNY',
  SEK: 'SEK',
  NZD: 'NZD',
  MXN: 'MXN',
  SGD: 'SGD',
  HKD: 'HKD',
  NOK: 'NOK',
  KRW: 'KRW',
  TRY: 'TRY',
  RUB: 'RUB',
  INR: 'INR',
  BRL: 'BRL',
  ZAR: 'ZAR',
  DKK: 'DKK',
  PLN: 'PLN',
  THB: 'THB',
  IDR: 'IDR',
  HUF: 'HUF',
  CZK: 'CZK',
  ILS: 'ILS',
  PHP: 'PHP',
  AED: 'AED',
  COP: 'COP',
  SAR: 'SAR',
  MYR: 'MYR',
  RON: 'RON'
} as const

export type Currency = (typeof Currency)[keyof typeof Currency]


export const OrderFulfilmentMethod = {
  delivery: 'delivery',
  pickup: 'pickup'
} as const

export type OrderFulfilmentMethod = (typeof OrderFulfilmentMethod)[keyof typeof OrderFulfilmentMethod]


export const OrderStatus = {
  draft: 'draft',
  pending: 'pending',
  confirmed: 'confirmed',
  completed: 'completed',
  cancelled: 'cancelled'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]


export const PaymentStatus = {
  pending: 'pending',
  succeeded: 'succeeded',
  refunded: 'refunded',
  failed: 'failed',
  canceled: 'canceled'
} as const

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus]


export const PaymentProvider = {
  stripe: 'stripe',
  revolut: 'revolut',
  payu: 'payu',
  not_applicable: 'not_applicable'
} as const

export type PaymentProvider = (typeof PaymentProvider)[keyof typeof PaymentProvider]


export const PaymentMethod = {
  card: 'card',
  blik: 'blik',
  paypal: 'paypal',
  bank_transfer: 'bank_transfer',
  cash_on_delivery: 'cash_on_delivery'
} as const

export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod]


export const CampaignType = {
  discount: 'discount',
  promotion: 'promotion'
} as const

export type CampaignType = (typeof CampaignType)[keyof typeof CampaignType]
