import type { Metadata } from "next";
import { Inter, Red_Hat_Display } from "next/font/google";
import React from "react";

import { Navbar } from "@/components/Navbar";
import { AppProvider } from "@/components/provider/app-provider";

import "../css/globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const redhat = Red_Hat_Display({
  subsets: ["latin"],
  variable: "--font-red-hat-display",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${redhat.variable} font-inter antialiased bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-100 tracking-tight`}
      >
        <AppProvider locale="en">
          <main className="min-h-screen bg-white dark:bg-black">
            <div className="flex flex-col min-h-screen">
              <Navbar />
              {children}
            </div>
          </main>
        </AppProvider>
      </body>
    </html>
  );
}
